version: 1.0.{build}
image: Ubuntu
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
  - sh: dotnet tool install --global dotnet-sonarscanner
before_build:
  - sh: dotnet sonarscanner begin /k:mickaelseban_DesignPatterns /v:$APPVEYOR_BUILD_VERSION /o:mickaelseban /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=407a1c9b2661cfbdf789b17d1855f05048093fe7 /d:sonar.cs.opencover.reportsPaths="*.opencover.xml"
build_script:
  - sh: dotnet restore DesignPatterns-Demo.sln --no-cache
  - sh: dotnet build DesignPatterns-Demo.sln --no-restore
test_script:
  - sh: dotnet test test/Behavioral.Tests --no-build /p:CollectCoverage=true /p:CoverletOutputFormat="opencover" /p:CoverletOutput=../../tests-coverage
  - sh: dotnet test test/Creational.Tests --no-build /p:CollectCoverage=true /p:CoverletOutputFormat="opencover" /p:CoverletOutput=../../tests-coverage
  - sh: dotnet test test/Structural.Tests --no-build /p:CollectCoverage=true /p:CoverletOutputFormat="opencover" /p:CoverletOutput=../../tests-coverage
after_test:
  - sh: dotnet sonarscanner end /d:sonar.login=407a1c9b2661cfbdf789b17d1855f05048093fe7